//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLearningCoreService
{
    using System.Diagnostics;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.phm.co.uk/types/common/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.CreateFeedRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.UpdateFeedRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.DeleteFeedRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.GetFeedsRequest))]
    public partial class RequestBase : object
    {
        
        private string AccessTokenField;
        
        private string CurrentCultureField;
        
        private string CurrentUICultureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentCulture
        {
            get
            {
                return this.CurrentCultureField;
            }
            set
            {
                this.CurrentCultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentUICulture
        {
            get
            {
                return this.CurrentUICultureField;
            }
            set
            {
                this.CurrentUICultureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateFeedRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class CreateFeedRequest : MLearningCoreService.RequestBase
    {
        
        private MLearningCoreService.BaseFeedDto CurrentFeedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.BaseFeedDto CurrentFeed
        {
            get
            {
                return this.CurrentFeedField;
            }
            set
            {
                this.CurrentFeedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateFeedRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class UpdateFeedRequest : MLearningCoreService.RequestBase
    {
        
        private MLearningCoreService.BaseFeedDto CurrentFeedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.BaseFeedDto CurrentFeed
        {
            get
            {
                return this.CurrentFeedField;
            }
            set
            {
                this.CurrentFeedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteFeedRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class DeleteFeedRequest : MLearningCoreService.RequestBase
    {
        
        private int FeedIdField;
        
        private bool ForceDeleteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeedId
        {
            get
            {
                return this.FeedIdField;
            }
            set
            {
                this.FeedIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceDelete
        {
            get
            {
                return this.ForceDeleteField;
            }
            set
            {
                this.ForceDeleteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFeedsRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class GetFeedsRequest : MLearningCoreService.RequestBase
    {
        
        private MLearningCoreService.FeedCriteriaDto CriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.FeedCriteriaDto Criteria
        {
            get
            {
                return this.CriteriaField;
            }
            set
            {
                this.CriteriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedCriteriaDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class FeedCriteriaDto : MLearningCoreService.BaseCriteriaDto
    {
        
        private System.Nullable<System.DateTime> DayField;
        
        private System.Nullable<int> IdField;
        
        private System.Nullable<bool> IsFavouriteField;
        
        private System.Nullable<int> MarketIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Day
        {
            get
            {
                return this.DayField;
            }
            set
            {
                this.DayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsFavourite
        {
            get
            {
                return this.IsFavouriteField;
            }
            set
            {
                this.IsFavouriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MarketId
        {
            get
            {
                return this.MarketIdField;
            }
            set
            {
                this.MarketIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFeedDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.ImageFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.TextFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.VideoFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.QuizFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.SurveyFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.LinkFeedDto))]
    public partial class BaseFeedDto : MLearningCoreService.BaseDtoOfint
    {
        
        private bool AllowFavouriteField;
        
        private MLearningCoreService.CorporateAppDto CorporateAppField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private MLearningCoreService.FeedCategoryEnumDto FeedCategoryField;
        
        private MLearningCoreService.FeedTypeEnumDto FeedTypeField;
        
        private bool IsFavouriteField;
        
        private string LegalInformationField;
        
        private MLearningCoreService.MediaInfoDto MainIconField;
        
        private System.Nullable<int> MainIconIdField;
        
        private bool MakeTitleWidgetLinkField;
        
        private int MarketIdField;
        
        private long PermissionsField;
        
        private int PointsField;
        
        private int ReadingTimeField;
        
        private string ShortDescriptionField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string TitleField;
        
        private string WebUrlLinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowFavourite
        {
            get
            {
                return this.AllowFavouriteField;
            }
            set
            {
                this.AllowFavouriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.CorporateAppDto CorporateApp
        {
            get
            {
                return this.CorporateAppField;
            }
            set
            {
                this.CorporateAppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.FeedCategoryEnumDto FeedCategory
        {
            get
            {
                return this.FeedCategoryField;
            }
            set
            {
                this.FeedCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.FeedTypeEnumDto FeedType
        {
            get
            {
                return this.FeedTypeField;
            }
            set
            {
                this.FeedTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFavourite
        {
            get
            {
                return this.IsFavouriteField;
            }
            set
            {
                this.IsFavouriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalInformation
        {
            get
            {
                return this.LegalInformationField;
            }
            set
            {
                this.LegalInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.MediaInfoDto MainIcon
        {
            get
            {
                return this.MainIconField;
            }
            set
            {
                this.MainIconField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MainIconId
        {
            get
            {
                return this.MainIconIdField;
            }
            set
            {
                this.MainIconIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MakeTitleWidgetLink
        {
            get
            {
                return this.MakeTitleWidgetLinkField;
            }
            set
            {
                this.MakeTitleWidgetLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketId
        {
            get
            {
                return this.MarketIdField;
            }
            set
            {
                this.MarketIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Permissions
        {
            get
            {
                return this.PermissionsField;
            }
            set
            {
                this.PermissionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReadingTime
        {
            get
            {
                return this.ReadingTimeField;
            }
            set
            {
                this.ReadingTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription
        {
            get
            {
                return this.ShortDescriptionField;
            }
            set
            {
                this.ShortDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebUrlLink
        {
            get
            {
                return this.WebUrlLinkField;
            }
            set
            {
                this.WebUrlLinkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDtoOfint", Namespace="http://schemas.datacontract.org/2004/07/Phm.Common.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.MediaInfoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.CorporateAppDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.QuizQuestionDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.QuizQuestionAnswerDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.SurveyQuestionDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.SurveyQuestionAnswerDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.BaseFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.ImageFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.TextFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.VideoFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.QuizFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.SurveyFeedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.LinkFeedDto))]
    public partial class BaseDtoOfint : object
    {
        
        private System.DateTime CreatedAtField;
        
        private System.Nullable<System.DateTime> DeletedAtField;
        
        private bool EnabledField;
        
        private int IdField;
        
        private System.Nullable<System.Guid> MasterIdField;
        
        private bool PublishedField;
        
        private System.DateTime UpdatedAtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeletedAt
        {
            get
            {
                return this.DeletedAtField;
            }
            set
            {
                this.DeletedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled
        {
            get
            {
                return this.EnabledField;
            }
            set
            {
                this.EnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> MasterId
        {
            get
            {
                return this.MasterIdField;
            }
            set
            {
                this.MasterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published
        {
            get
            {
                return this.PublishedField;
            }
            set
            {
                this.PublishedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaInfoDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class MediaInfoDto : MLearningCoreService.BaseDtoOfint
    {
        
        private string AzureUrlField;
        
        private string ExtensionField;
        
        private int MarketIdField;
        
        private string MediaIdField;
        
        private MLearningCoreService.MediaTypesDto MediaTypeField;
        
        private int MediaVersionField;
        
        private string NameField;
        
        private string PathField;
        
        private string Preview1PathField;
        
        private long SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AzureUrl
        {
            get
            {
                return this.AzureUrlField;
            }
            set
            {
                this.AzureUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketId
        {
            get
            {
                return this.MarketIdField;
            }
            set
            {
                this.MarketIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MediaId
        {
            get
            {
                return this.MediaIdField;
            }
            set
            {
                this.MediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.MediaTypesDto MediaType
        {
            get
            {
                return this.MediaTypeField;
            }
            set
            {
                this.MediaTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaVersion
        {
            get
            {
                return this.MediaVersionField;
            }
            set
            {
                this.MediaVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Preview1Path
        {
            get
            {
                return this.Preview1PathField;
            }
            set
            {
                this.Preview1PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorporateAppDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class CorporateAppDto : MLearningCoreService.BaseDtoOfint
    {
        
        private MLearningCoreService.AppTypeEnumDto AppTypeField;
        
        private string LinkUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.AppTypeEnumDto AppType
        {
            get
            {
                return this.AppTypeField;
            }
            set
            {
                this.AppTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkUrl
        {
            get
            {
                return this.LinkUrlField;
            }
            set
            {
                this.LinkUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizQuestionDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class QuizQuestionDto : MLearningCoreService.BaseDtoOfint
    {
        
        private System.Collections.Generic.List<MLearningCoreService.QuizQuestionAnswerDto> AnswersField;
        
        private int OrderField;
        
        private string QuestionField;
        
        private MLearningCoreService.QuizQuestionTypeEnumDto QuestionTypeField;
        
        private int QuizFeedIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MLearningCoreService.QuizQuestionAnswerDto> Answers
        {
            get
            {
                return this.AnswersField;
            }
            set
            {
                this.AnswersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question
        {
            get
            {
                return this.QuestionField;
            }
            set
            {
                this.QuestionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.QuizQuestionTypeEnumDto QuestionType
        {
            get
            {
                return this.QuestionTypeField;
            }
            set
            {
                this.QuestionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuizFeedId
        {
            get
            {
                return this.QuizFeedIdField;
            }
            set
            {
                this.QuizFeedIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizQuestionAnswerDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class QuizQuestionAnswerDto : MLearningCoreService.BaseDtoOfint
    {
        
        private string AnswerField;
        
        private bool IsCorrectField;
        
        private int OrderField;
        
        private int QuizQuestionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer
        {
            get
            {
                return this.AnswerField;
            }
            set
            {
                this.AnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCorrect
        {
            get
            {
                return this.IsCorrectField;
            }
            set
            {
                this.IsCorrectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuizQuestionId
        {
            get
            {
                return this.QuizQuestionIdField;
            }
            set
            {
                this.QuizQuestionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyQuestionDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class SurveyQuestionDto : MLearningCoreService.BaseDtoOfint
    {
        
        private System.Collections.Generic.List<MLearningCoreService.SurveyQuestionAnswerDto> AnswersField;
        
        private int OrderField;
        
        private string QuestionField;
        
        private MLearningCoreService.SurveyQuestionTypeEnumDto QuestionTypeField;
        
        private int SurveyFeedIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MLearningCoreService.SurveyQuestionAnswerDto> Answers
        {
            get
            {
                return this.AnswersField;
            }
            set
            {
                this.AnswersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question
        {
            get
            {
                return this.QuestionField;
            }
            set
            {
                this.QuestionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.SurveyQuestionTypeEnumDto QuestionType
        {
            get
            {
                return this.QuestionTypeField;
            }
            set
            {
                this.QuestionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyFeedId
        {
            get
            {
                return this.SurveyFeedIdField;
            }
            set
            {
                this.SurveyFeedIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyQuestionAnswerDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class SurveyQuestionAnswerDto : MLearningCoreService.BaseDtoOfint
    {
        
        private string AnswerField;
        
        private bool IsFreeTextField;
        
        private int OrderField;
        
        private int SurveyQuestionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer
        {
            get
            {
                return this.AnswerField;
            }
            set
            {
                this.AnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFreeText
        {
            get
            {
                return this.IsFreeTextField;
            }
            set
            {
                this.IsFreeTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyQuestionId
        {
            get
            {
                return this.SurveyQuestionIdField;
            }
            set
            {
                this.SurveyQuestionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageFeedDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class ImageFeedDto : MLearningCoreService.BaseFeedDto
    {
        
        private string ImageDescriptionField;
        
        private MLearningCoreService.MediaInfoDto MainImageField;
        
        private System.Nullable<int> MainImageIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageDescription
        {
            get
            {
                return this.ImageDescriptionField;
            }
            set
            {
                this.ImageDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.MediaInfoDto MainImage
        {
            get
            {
                return this.MainImageField;
            }
            set
            {
                this.MainImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MainImageId
        {
            get
            {
                return this.MainImageIdField;
            }
            set
            {
                this.MainImageIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextFeedDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class TextFeedDto : MLearningCoreService.BaseFeedDto
    {
        
        private string BodyTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyText
        {
            get
            {
                return this.BodyTextField;
            }
            set
            {
                this.BodyTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VideoFeedDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class VideoFeedDto : MLearningCoreService.BaseFeedDto
    {
        
        private MLearningCoreService.MediaInfoDto MainVideoField;
        
        private System.Nullable<int> MainVideoIdField;
        
        private string VideoDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.MediaInfoDto MainVideo
        {
            get
            {
                return this.MainVideoField;
            }
            set
            {
                this.MainVideoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MainVideoId
        {
            get
            {
                return this.MainVideoIdField;
            }
            set
            {
                this.MainVideoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoDescription
        {
            get
            {
                return this.VideoDescriptionField;
            }
            set
            {
                this.VideoDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizFeedDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class QuizFeedDto : MLearningCoreService.BaseFeedDto
    {
        
        private string FailMessageField;
        
        private string OnBoardingMessageField;
        
        private System.Collections.Generic.List<MLearningCoreService.QuizQuestionDto> QuestionsField;
        
        private string QuizDescriptionField;
        
        private string SuccessMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailMessage
        {
            get
            {
                return this.FailMessageField;
            }
            set
            {
                this.FailMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OnBoardingMessage
        {
            get
            {
                return this.OnBoardingMessageField;
            }
            set
            {
                this.OnBoardingMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MLearningCoreService.QuizQuestionDto> Questions
        {
            get
            {
                return this.QuestionsField;
            }
            set
            {
                this.QuestionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuizDescription
        {
            get
            {
                return this.QuizDescriptionField;
            }
            set
            {
                this.QuizDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessMessage
        {
            get
            {
                return this.SuccessMessageField;
            }
            set
            {
                this.SuccessMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyFeedDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class SurveyFeedDto : MLearningCoreService.BaseFeedDto
    {
        
        private System.Collections.Generic.List<MLearningCoreService.SurveyQuestionDto> QuestionsField;
        
        private string SurveyDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MLearningCoreService.SurveyQuestionDto> Questions
        {
            get
            {
                return this.QuestionsField;
            }
            set
            {
                this.QuestionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurveyDescription
        {
            get
            {
                return this.SurveyDescriptionField;
            }
            set
            {
                this.SurveyDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkFeedDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class LinkFeedDto : MLearningCoreService.BaseFeedDto
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedCategoryEnumDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public enum FeedCategoryEnumDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Learning = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        News = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Campaign = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Announcement = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Article = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedTypeEnumDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public enum FeedTypeEnumDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Video = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quiz = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Survey = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VideoLink = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImageLink = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfLink = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaTypesDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public enum MediaTypesDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Font = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Video = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Icon = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppTypeEnumDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public enum AppTypeEnumDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FISA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CCESG = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MLearning = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizQuestionTypeEnumDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public enum QuizQuestionTypeEnumDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multiple = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyQuestionTypeEnumDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public enum SurveyQuestionTypeEnumDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multiple = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCriteriaDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Common.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MLearningCoreService.FeedCriteriaDto))]
    public partial class BaseCriteriaDto : object
    {
        
        private System.Nullable<bool> DeletedField;
        
        private System.Nullable<bool> EnabledField;
        
        private string OrdetByField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        private System.Nullable<bool> PublishedField;
        
        private System.Nullable<bool> ValidVersionField;
        
        private System.Nullable<int> VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Enabled
        {
            get
            {
                return this.EnabledField;
            }
            set
            {
                this.EnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdetBy
        {
            get
            {
                return this.OrdetByField;
            }
            set
            {
                this.OrdetByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Published
        {
            get
            {
                return this.PublishedField;
            }
            set
            {
                this.PublishedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ValidVersion
        {
            get
            {
                return this.ValidVersionField;
            }
            set
            {
                this.ValidVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFeedsResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class GetFeedsResponse : object
    {
        
        private System.Collections.Generic.List<MLearningCoreService.BaseFeedDto> FeedsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MLearningCoreService.BaseFeedDto> Feeds
        {
            get
            {
                return this.FeedsField;
            }
            set
            {
                this.FeedsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
    public partial class BaseError : object
    {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private System.Collections.Generic.List<string> ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateFeedResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class CreateFeedResponse : object
    {
        
        private MLearningCoreService.BaseFeedDto CurrentFeedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.BaseFeedDto CurrentFeed
        {
            get
            {
                return this.CurrentFeedField;
            }
            set
            {
                this.CurrentFeedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateFeedResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class UpdateFeedResponse : object
    {
        
        private MLearningCoreService.BaseFeedDto CurrentBaseFeedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MLearningCoreService.BaseFeedDto CurrentBaseFeed
        {
            get
            {
                return this.CurrentBaseFeedField;
            }
            set
            {
                this.CurrentBaseFeedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteFeedResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.MLearning")]
    public partial class DeleteFeedResponse : object
    {
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MLearningCoreService.IMLearningCoreContract")]
    public interface IMLearningCoreContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMLearningCoreContract/GetFeeds", ReplyAction="http://tempuri.org/IMLearningCoreContract/GetFeedsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MLearningCoreService.BaseError), Action="http://tempuri.org/IMLearningCoreContract/GetFeedsBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<MLearningCoreService.GetFeedsResponse> GetFeedsAsync(MLearningCoreService.GetFeedsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMLearningCoreContract/CreateFeed", ReplyAction="http://tempuri.org/IMLearningCoreContract/CreateFeedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MLearningCoreService.BaseError), Action="http://tempuri.org/IMLearningCoreContract/CreateFeedBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<MLearningCoreService.CreateFeedResponse> CreateFeedAsync(MLearningCoreService.CreateFeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMLearningCoreContract/UpdateFeed", ReplyAction="http://tempuri.org/IMLearningCoreContract/UpdateFeedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MLearningCoreService.BaseError), Action="http://tempuri.org/IMLearningCoreContract/UpdateFeedBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<MLearningCoreService.UpdateFeedResponse> UpdateFeedAsync(MLearningCoreService.UpdateFeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMLearningCoreContract/DeleteFeed", ReplyAction="http://tempuri.org/IMLearningCoreContract/DeleteFeedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MLearningCoreService.BaseError), Action="http://tempuri.org/IMLearningCoreContract/DeleteFeedBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<MLearningCoreService.DeleteFeedResponse> DeleteFeedAsync(MLearningCoreService.DeleteFeedRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IMLearningCoreContractChannel : MLearningCoreService.IMLearningCoreContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class MLearningCoreContractClient : System.ServiceModel.ClientBase<MLearningCoreService.IMLearningCoreContract>, MLearningCoreService.IMLearningCoreContract
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MLearningCoreContractClient() : 
                base(MLearningCoreContractClient.GetDefaultBinding(), MLearningCoreContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MLearningCoreServiceEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MLearningCoreContractClient(EndpointConfiguration endpointConfiguration) : 
                base(MLearningCoreContractClient.GetBindingForEndpoint(endpointConfiguration), MLearningCoreContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MLearningCoreContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MLearningCoreContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MLearningCoreContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MLearningCoreContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MLearningCoreContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MLearningCoreService.GetFeedsResponse> GetFeedsAsync(MLearningCoreService.GetFeedsRequest request)
        {
            return base.Channel.GetFeedsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLearningCoreService.CreateFeedResponse> CreateFeedAsync(MLearningCoreService.CreateFeedRequest request)
        {
            return base.Channel.CreateFeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLearningCoreService.UpdateFeedResponse> UpdateFeedAsync(MLearningCoreService.UpdateFeedRequest request)
        {
            return base.Channel.UpdateFeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLearningCoreService.DeleteFeedResponse> DeleteFeedAsync(MLearningCoreService.DeleteFeedRequest request)
        {
            return base.Channel.DeleteFeedAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MLearningCoreServiceEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MLearningCoreServiceEndpoint))
            {
#if DEBUG
                return new System.ServiceModel.EndpointAddress("http://ccesg20.phm.co.uk/mobile/MLearningCoreService.svc");
#else
                return new System.ServiceModel.EndpointAddress("http://mobilespapi-staging.azurewebsites.net/MLearningCoreService.svc");
#endif
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MLearningCoreContractClient.GetBindingForEndpoint(EndpointConfiguration.MLearningCoreServiceEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MLearningCoreContractClient.GetEndpointAddress(EndpointConfiguration.MLearningCoreServiceEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            MLearningCoreServiceEndpoint,
        }
    }
}
