//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.phm.co.uk/types/common/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.GetUserTemplates1Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.CreateUserTemplate1Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.UpdateUserTemplate1Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.CreateSecGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.UpdateSecGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.DeleteSecGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.AddUserInSecGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.RemoveUserFromSecGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.GetUsersInSecGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.AddPermissionsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.RemovePermissionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.GetSecGroupsRequest))]
    public partial class RequestBase : object
    {
        
        private string AccessTokenField;
        
        private string CurrentCultureField;
        
        private string CurrentUICultureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentCulture
        {
            get
            {
                return this.CurrentCultureField;
            }
            set
            {
                this.CurrentCultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentUICulture
        {
            get
            {
                return this.CurrentUICultureField;
            }
            set
            {
                this.CurrentUICultureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserTemplates1Request", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Security")]
    public partial class GetUserTemplates1Request : SecurityService.RequestBase
    {
        
        private SecurityService.UserTemplate1CriteriaDto CriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.UserTemplate1CriteriaDto Criteria
        {
            get
            {
                return this.CriteriaField;
            }
            set
            {
                this.CriteriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateUserTemplate1Request", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Security")]
    public partial class CreateUserTemplate1Request : SecurityService.RequestBase
    {
        
        private SecurityService.UserTemplate1Dto CurrentUserTemplate1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.UserTemplate1Dto CurrentUserTemplate1
        {
            get
            {
                return this.CurrentUserTemplate1Field;
            }
            set
            {
                this.CurrentUserTemplate1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateUserTemplate1Request", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Security")]
    public partial class UpdateUserTemplate1Request : SecurityService.RequestBase
    {
        
        private SecurityService.UserTemplate1Dto CurrentUserTemplate1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.UserTemplate1Dto CurrentUserTemplate1
        {
            get
            {
                return this.CurrentUserTemplate1Field;
            }
            set
            {
                this.CurrentUserTemplate1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateSecGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class CreateSecGroupRequest : SecurityService.RequestBase
    {
        
        private SecurityService.SecGroupDto CurrentSecGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.SecGroupDto CurrentSecGroup
        {
            get
            {
                return this.CurrentSecGroupField;
            }
            set
            {
                this.CurrentSecGroupField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateSecGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class UpdateSecGroupRequest : SecurityService.RequestBase
    {
        
        private SecurityService.SecGroupDto CurrentSecGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.SecGroupDto CurrentSecGroup
        {
            get
            {
                return this.CurrentSecGroupField;
            }
            set
            {
                this.CurrentSecGroupField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteSecGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class DeleteSecGroupRequest : SecurityService.RequestBase
    {
        
        private bool ForceDeleteField;
        
        private int SecGroupIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceDelete
        {
            get
            {
                return this.ForceDeleteField;
            }
            set
            {
                this.ForceDeleteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecGroupId
        {
            get
            {
                return this.SecGroupIdField;
            }
            set
            {
                this.SecGroupIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddUserInSecGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class AddUserInSecGroupRequest : SecurityService.RequestBase
    {
        
        private int SecGroupIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecGroupId
        {
            get
            {
                return this.SecGroupIdField;
            }
            set
            {
                this.SecGroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveUserFromSecGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class RemoveUserFromSecGroupRequest : SecurityService.RequestBase
    {
        
        private int SecGroupIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecGroupId
        {
            get
            {
                return this.SecGroupIdField;
            }
            set
            {
                this.SecGroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersInSecGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class GetUsersInSecGroupRequest : SecurityService.RequestBase
    {
        
        private int SecGroupIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecGroupId
        {
            get
            {
                return this.SecGroupIdField;
            }
            set
            {
                this.SecGroupIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddPermissionsRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class AddPermissionsRequest : SecurityService.RequestBase
    {
        
        private SecurityService.SecPermissionDto CurrentSecPermissionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.SecPermissionDto CurrentSecPermission
        {
            get
            {
                return this.CurrentSecPermissionField;
            }
            set
            {
                this.CurrentSecPermissionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemovePermissionRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class RemovePermissionRequest : SecurityService.RequestBase
    {
        
        private int SecPermissionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecPermissionId
        {
            get
            {
                return this.SecPermissionIdField;
            }
            set
            {
                this.SecPermissionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSecGroupsRequest", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class GetSecGroupsRequest : SecurityService.RequestBase
    {
        
        private SecurityService.SecGroupCriteriaDto CriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.SecGroupCriteriaDto Criteria
        {
            get
            {
                return this.CriteriaField;
            }
            set
            {
                this.CriteriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecGroupCriteriaDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Criteria")]
    public partial class SecGroupCriteriaDto : SecurityService.BaseCriteriaDto
    {
        
        private System.Nullable<int> MarketIdField;
        
        private string NameField;
        
        private System.Nullable<int> SecGroupIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MarketId
        {
            get
            {
                return this.MarketIdField;
            }
            set
            {
                this.MarketIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecGroupId
        {
            get
            {
                return this.SecGroupIdField;
            }
            set
            {
                this.SecGroupIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTemplate1CriteriaDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Criteria")]
    public partial class UserTemplate1CriteriaDto : object
    {
        
        private int MarketIdField;
        
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketId
        {
            get
            {
                return this.MarketIdField;
            }
            set
            {
                this.MarketIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTemplate1Dto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Security")]
    public partial class UserTemplate1Dto : SecurityService.BaseDtoOfint
    {
        
        private string AreaCodeField;
        
        private string AreaNameField;
        
        private SecurityService.MediaInfoDto AvatarField;
        
        private System.Nullable<int> AvatarIdField;
        
        private string DealershipCodeField;
        
        private string DealershipNameField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string RegionCodeField;
        
        private string RegionNameField;
        
        private SecurityService.SecGroupNM1Dto SecGroupField;
        
        private int TotalMLearningPointsField;
        
        private string UserNameField;
        
        private string ZoneCodeField;
        
        private string ZoneNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode
        {
            get
            {
                return this.AreaCodeField;
            }
            set
            {
                this.AreaCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaName
        {
            get
            {
                return this.AreaNameField;
            }
            set
            {
                this.AreaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.MediaInfoDto Avatar
        {
            get
            {
                return this.AvatarField;
            }
            set
            {
                this.AvatarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AvatarId
        {
            get
            {
                return this.AvatarIdField;
            }
            set
            {
                this.AvatarIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealershipCode
        {
            get
            {
                return this.DealershipCodeField;
            }
            set
            {
                this.DealershipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealershipName
        {
            get
            {
                return this.DealershipNameField;
            }
            set
            {
                this.DealershipNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionCode
        {
            get
            {
                return this.RegionCodeField;
            }
            set
            {
                this.RegionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.SecGroupNM1Dto SecGroup
        {
            get
            {
                return this.SecGroupField;
            }
            set
            {
                this.SecGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalMLearningPoints
        {
            get
            {
                return this.TotalMLearningPointsField;
            }
            set
            {
                this.TotalMLearningPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZoneCode
        {
            get
            {
                return this.ZoneCodeField;
            }
            set
            {
                this.ZoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZoneName
        {
            get
            {
                return this.ZoneNameField;
            }
            set
            {
                this.ZoneNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDtoOfint", Namespace="http://schemas.datacontract.org/2004/07/Phm.Common.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.SecGroupDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.UserDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.SecPermissionDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.MediaInfoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.UserTemplate1Dto))]
    public partial class BaseDtoOfint : object
    {
        
        private System.DateTime CreatedAtField;
        
        private System.Nullable<System.DateTime> DeletedAtField;
        
        private bool EnabledField;
        
        private int IdField;
        
        private System.Nullable<System.Guid> MasterIdField;
        
        private bool PublishedField;
        
        private System.DateTime UpdatedAtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeletedAt
        {
            get
            {
                return this.DeletedAtField;
            }
            set
            {
                this.DeletedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled
        {
            get
            {
                return this.EnabledField;
            }
            set
            {
                this.EnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> MasterId
        {
            get
            {
                return this.MasterIdField;
            }
            set
            {
                this.MasterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published
        {
            get
            {
                return this.PublishedField;
            }
            set
            {
                this.PublishedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecGroupDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class SecGroupDto : SecurityService.BaseDtoOfint
    {
        
        private string DescriptionField;
        
        private bool IsBuiltInField;
        
        private int MaxUserCountField;
        
        private string NameField;
        
        private System.Nullable<int> SecEntityIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBuiltIn
        {
            get
            {
                return this.IsBuiltInField;
            }
            set
            {
                this.IsBuiltInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxUserCount
        {
            get
            {
                return this.MaxUserCountField;
            }
            set
            {
                this.MaxUserCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecEntityId
        {
            get
            {
                return this.SecEntityIdField;
            }
            set
            {
                this.SecEntityIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class UserDto : SecurityService.BaseDtoOfint
    {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private bool IsBuiltInField;
        
        private string LastNameField;
        
        private System.Nullable<int> SecEntityIdField;
        
        private int SessionExpireMinutesField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBuiltIn
        {
            get
            {
                return this.IsBuiltInField;
            }
            set
            {
                this.IsBuiltInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecEntityId
        {
            get
            {
                return this.SecEntityIdField;
            }
            set
            {
                this.SecEntityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionExpireMinutes
        {
            get
            {
                return this.SessionExpireMinutesField;
            }
            set
            {
                this.SessionExpireMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecPermissionDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class SecPermissionDto : SecurityService.BaseDtoOfint
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaInfoDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class MediaInfoDto : SecurityService.BaseDtoOfint
    {
        
        private string AzureUrlField;
        
        private string ExtensionField;
        
        private int MarketIdField;
        
        private string MediaIdField;
        
        private SecurityService.MediaTypesDto MediaTypeField;
        
        private int MediaVersionField;
        
        private string NameField;
        
        private string PathField;
        
        private string Preview1PathField;
        
        private long SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AzureUrl
        {
            get
            {
                return this.AzureUrlField;
            }
            set
            {
                this.AzureUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketId
        {
            get
            {
                return this.MarketIdField;
            }
            set
            {
                this.MarketIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MediaId
        {
            get
            {
                return this.MediaIdField;
            }
            set
            {
                this.MediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.MediaTypesDto MediaType
        {
            get
            {
                return this.MediaTypeField;
            }
            set
            {
                this.MediaTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaVersion
        {
            get
            {
                return this.MediaVersionField;
            }
            set
            {
                this.MediaVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Preview1Path
        {
            get
            {
                return this.Preview1PathField;
            }
            set
            {
                this.Preview1PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecGroupNM1Dto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Security")]
    public partial class SecGroupNM1Dto : object
    {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaTypesDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public enum MediaTypesDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Font = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Video = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Icon = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCriteriaDto", Namespace="http://schemas.datacontract.org/2004/07/Phm.Common.Dto")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityService.SecGroupCriteriaDto))]
    public partial class BaseCriteriaDto : object
    {
        
        private System.Nullable<bool> DeletedField;
        
        private System.Nullable<bool> EnabledField;
        
        private string OrdetByField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        private System.Nullable<bool> PublishedField;
        
        private System.Nullable<bool> ValidVersionField;
        
        private System.Nullable<int> VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Enabled
        {
            get
            {
                return this.EnabledField;
            }
            set
            {
                this.EnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdetBy
        {
            get
            {
                return this.OrdetByField;
            }
            set
            {
                this.OrdetByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Published
        {
            get
            {
                return this.PublishedField;
            }
            set
            {
                this.PublishedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ValidVersion
        {
            get
            {
                return this.ValidVersionField;
            }
            set
            {
                this.ValidVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSecGroupsResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class GetSecGroupsResponse : object
    {
        
        private System.Collections.Generic.List<SecurityService.SecGroupDto> SecGroupsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SecurityService.SecGroupDto> SecGroups
        {
            get
            {
                return this.SecGroupsField;
            }
            set
            {
                this.SecGroupsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
    public partial class BaseError : object
    {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private System.Collections.Generic.List<string> ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateSecGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class CreateSecGroupResponse : object
    {
        
        private SecurityService.SecGroupDto CurrentSecGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.SecGroupDto CurrentSecGroup
        {
            get
            {
                return this.CurrentSecGroupField;
            }
            set
            {
                this.CurrentSecGroupField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateSecGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class UpdateSecGroupResponse : object
    {
        
        private SecurityService.SecGroupDto CurrentSecGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.SecGroupDto CurrentSecGroup
        {
            get
            {
                return this.CurrentSecGroupField;
            }
            set
            {
                this.CurrentSecGroupField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteSecGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class DeleteSecGroupResponse : object
    {
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddUserInSecGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class AddUserInSecGroupResponse : object
    {
        
        private bool AddedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Added
        {
            get
            {
                return this.AddedField;
            }
            set
            {
                this.AddedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveUserFromSecGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class RemoveUserFromSecGroupResponse : object
    {
        
        private bool RemovedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Removed
        {
            get
            {
                return this.RemovedField;
            }
            set
            {
                this.RemovedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersInSecGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class GetUsersInSecGroupResponse : object
    {
        
        private System.Collections.Generic.List<SecurityService.UserDto> UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SecurityService.UserDto> Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddPermissionsResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class AddPermissionsResponse : object
    {
        
        private SecurityService.SecPermissionDto CurrentSecPermissionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.SecPermissionDto CurrentSecPermission
        {
            get
            {
                return this.CurrentSecPermissionField;
            }
            set
            {
                this.CurrentSecPermissionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemovePermissionResponse", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data")]
    public partial class RemovePermissionResponse : object
    {
        
        private bool RemovedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Removed
        {
            get
            {
                return this.RemovedField;
            }
            set
            {
                this.RemovedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserTemplates1Response", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Security")]
    public partial class GetUserTemplates1Response : object
    {
        
        private System.Collections.Generic.List<SecurityService.UserTemplate1Dto> UserTemplates1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SecurityService.UserTemplate1Dto> UserTemplates1
        {
            get
            {
                return this.UserTemplates1Field;
            }
            set
            {
                this.UserTemplates1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateUserTemplate1Response", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Security")]
    public partial class CreateUserTemplate1Response : object
    {
        
        private bool CreatedField;
        
        private SecurityService.UserTemplate1Dto CurrentUserTemplate1Field;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Created
        {
            get
            {
                return this.CreatedField;
            }
            set
            {
                this.CreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.UserTemplate1Dto CurrentUserTemplate1
        {
            get
            {
                return this.CurrentUserTemplate1Field;
            }
            set
            {
                this.CurrentUserTemplate1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateUserTemplate1Response", Namespace="http://schemas.datacontract.org/2004/07/Phm.Ccesg2.CoreSvc.Api.Data.Security")]
    public partial class UpdateUserTemplate1Response : object
    {
        
        private SecurityService.UserTemplate1Dto CurrentUserTemplate1Field;
        
        private string MessageField;
        
        private bool UpdatedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecurityService.UserTemplate1Dto CurrentUserTemplate1
        {
            get
            {
                return this.CurrentUserTemplate1Field;
            }
            set
            {
                this.CurrentUserTemplate1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Updated
        {
            get
            {
                return this.UpdatedField;
            }
            set
            {
                this.UpdatedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityService.ISecurityContract")]
    public interface ISecurityContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/GetSecGroups", ReplyAction="http://tempuri.org/ISecurityContract/GetSecGroupsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/GetSecGroupsBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.GetSecGroupsResponse> GetSecGroupsAsync(SecurityService.GetSecGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/CreateSecGroup", ReplyAction="http://tempuri.org/ISecurityContract/CreateSecGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/CreateSecGroupBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.CreateSecGroupResponse> CreateSecGroupAsync(SecurityService.CreateSecGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/UpdateSecGroup", ReplyAction="http://tempuri.org/ISecurityContract/UpdateSecGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/UpdateSecGroupBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.UpdateSecGroupResponse> UpdateSecGroupAsync(SecurityService.UpdateSecGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/DeleteSecGroup", ReplyAction="http://tempuri.org/ISecurityContract/DeleteSecGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/DeleteSecGroupBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.DeleteSecGroupResponse> DeleteSecGroupAsync(SecurityService.DeleteSecGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/AddUserInSecGroup", ReplyAction="http://tempuri.org/ISecurityContract/AddUserInSecGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/AddUserInSecGroupBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.AddUserInSecGroupResponse> AddUserInSecGroupAsync(SecurityService.AddUserInSecGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/RemoveUserFromSecGroup", ReplyAction="http://tempuri.org/ISecurityContract/RemoveUserFromSecGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/RemoveUserFromSecGroupBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.RemoveUserFromSecGroupResponse> RemoveUserFromSecGroupAsync(SecurityService.RemoveUserFromSecGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/GetUsersInSecGroup", ReplyAction="http://tempuri.org/ISecurityContract/GetUsersInSecGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/GetUsersInSecGroupBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.GetUsersInSecGroupResponse> GetUsersInSecGroupAsync(SecurityService.GetUsersInSecGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/AddPermissions", ReplyAction="http://tempuri.org/ISecurityContract/AddPermissionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/AddPermissionsBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.AddPermissionsResponse> AddPermissionsAsync(SecurityService.AddPermissionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/RemovePermission", ReplyAction="http://tempuri.org/ISecurityContract/RemovePermissionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/RemovePermissionBaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.RemovePermissionResponse> RemovePermissionAsync(SecurityService.RemovePermissionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/GetUserTemplates1", ReplyAction="http://tempuri.org/ISecurityContract/GetUserTemplates1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/GetUserTemplates1BaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.GetUserTemplates1Response> GetUserTemplates1Async(SecurityService.GetUserTemplates1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/CreateUserTemplate1", ReplyAction="http://tempuri.org/ISecurityContract/CreateUserTemplate1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/CreateUserTemplate1BaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.CreateUserTemplate1Response> CreateUserTemplate1Async(SecurityService.CreateUserTemplate1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityContract/UpdateUserTemplate1", ReplyAction="http://tempuri.org/ISecurityContract/UpdateUserTemplate1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecurityService.BaseError), Action="http://tempuri.org/ISecurityContract/UpdateUserTemplate1BaseErrorFault", Name="BaseError", Namespace="http://www.phm.co.uk/types/common/")]
        System.Threading.Tasks.Task<SecurityService.UpdateUserTemplate1Response> UpdateUserTemplate1Async(SecurityService.UpdateUserTemplate1Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface ISecurityContractChannel : SecurityService.ISecurityContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class SecurityContractClient : System.ServiceModel.ClientBase<SecurityService.ISecurityContract>, SecurityService.ISecurityContract
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SecurityContractClient() : 
                base(SecurityContractClient.GetDefaultBinding(), SecurityContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISecurityContract.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityContractClient(EndpointConfiguration endpointConfiguration) : 
                base(SecurityContractClient.GetBindingForEndpoint(endpointConfiguration), SecurityContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SecurityContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SecurityContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SecurityService.GetSecGroupsResponse> GetSecGroupsAsync(SecurityService.GetSecGroupsRequest request)
        {
            return base.Channel.GetSecGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.CreateSecGroupResponse> CreateSecGroupAsync(SecurityService.CreateSecGroupRequest request)
        {
            return base.Channel.CreateSecGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.UpdateSecGroupResponse> UpdateSecGroupAsync(SecurityService.UpdateSecGroupRequest request)
        {
            return base.Channel.UpdateSecGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.DeleteSecGroupResponse> DeleteSecGroupAsync(SecurityService.DeleteSecGroupRequest request)
        {
            return base.Channel.DeleteSecGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.AddUserInSecGroupResponse> AddUserInSecGroupAsync(SecurityService.AddUserInSecGroupRequest request)
        {
            return base.Channel.AddUserInSecGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.RemoveUserFromSecGroupResponse> RemoveUserFromSecGroupAsync(SecurityService.RemoveUserFromSecGroupRequest request)
        {
            return base.Channel.RemoveUserFromSecGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.GetUsersInSecGroupResponse> GetUsersInSecGroupAsync(SecurityService.GetUsersInSecGroupRequest request)
        {
            return base.Channel.GetUsersInSecGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.AddPermissionsResponse> AddPermissionsAsync(SecurityService.AddPermissionsRequest request)
        {
            return base.Channel.AddPermissionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.RemovePermissionResponse> RemovePermissionAsync(SecurityService.RemovePermissionRequest request)
        {
            return base.Channel.RemovePermissionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.GetUserTemplates1Response> GetUserTemplates1Async(SecurityService.GetUserTemplates1Request request)
        {
            return base.Channel.GetUserTemplates1Async(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.CreateUserTemplate1Response> CreateUserTemplate1Async(SecurityService.CreateUserTemplate1Request request)
        {
            return base.Channel.CreateUserTemplate1Async(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.UpdateUserTemplate1Response> UpdateUserTemplate1Async(SecurityService.UpdateUserTemplate1Request request)
        {
            return base.Channel.UpdateUserTemplate1Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISecurityContract))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISecurityContract))
            {
                return new System.ServiceModel.EndpointAddress("http://mobilespapi.phm.co.uk/SecurityService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SecurityContractClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISecurityContract);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SecurityContractClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISecurityContract);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISecurityContract,
        }
    }
}
